spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dictionary_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/main-changelog.yml
